/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as MomentIdRouteImport } from './routes/moment.$id'
import { Route as MomentCreateRouteImport } from './routes/moment.create'
import { Route as PartnerProfileRouteImport } from './routes/partner.profile'
import { Route as PartnerRequestRouteImport } from './routes/partner.request'
import { Route as VenueIdRouteImport } from './routes/venue.$id'
import { Route as AdminVenuesAddRouteImport } from './routes/admin.venues.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentIdRoute = MomentIdRouteImport.update({
  id: '/moment/$id',
  path: '/moment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentCreateRoute = MomentCreateRouteImport.update({
  id: '/moment/create',
  path: '/moment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerRequestRoute = PartnerRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => PartnerRoute,
} as any)
const VenueIdRoute = VenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesAddRoute = AdminVenuesAddRouteImport.update({
  id: '/venues/add',
  path: '/venues/add',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/moments': typeof MomentsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/event/$id': typeof EventIdRoute
  '/moment/$id': typeof MomentIdRoute
  '/moment/create': typeof MomentCreateRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/request': typeof PartnerRequestRoute
  '/venue/$id': typeof VenueIdRoute
  '/admin/venues/add': typeof AdminVenuesAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/moments': typeof MomentsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/event/$id': typeof EventIdRoute
  '/moment/$id': typeof MomentIdRoute
  '/moment/create': typeof MomentCreateRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/request': typeof PartnerRequestRoute
  '/venue/$id': typeof VenueIdRoute
  '/admin/venues/add': typeof AdminVenuesAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/moments': typeof MomentsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/event/$id': typeof EventIdRoute
  '/moment/$id': typeof MomentIdRoute
  '/moment/create': typeof MomentCreateRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/request': typeof PartnerRequestRoute
  '/venue/$id': typeof VenueIdRoute
  '/admin/venues/add': typeof AdminVenuesAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/chat'
    | '/explore'
    | '/home'
    | '/moments'
    | '/partner'
    | '/profile'
    | '/report'
    | '/admin/partners'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/event/$id'
    | '/moment/$id'
    | '/moment/create'
    | '/partner/profile'
    | '/partner/request'
    | '/venue/$id'
    | '/admin/venues/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booking'
    | '/chat'
    | '/explore'
    | '/home'
    | '/moments'
    | '/partner'
    | '/profile'
    | '/report'
    | '/admin/partners'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/event/$id'
    | '/moment/$id'
    | '/moment/create'
    | '/partner/profile'
    | '/partner/request'
    | '/venue/$id'
    | '/admin/venues/add'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/chat'
    | '/explore'
    | '/home'
    | '/moments'
    | '/partner'
    | '/profile'
    | '/report'
    | '/admin/partners'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/event/$id'
    | '/moment/$id'
    | '/moment/create'
    | '/partner/profile'
    | '/partner/request'
    | '/venue/$id'
    | '/admin/venues/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  HomeRoute: typeof HomeRoute
  MomentsRoute: typeof MomentsRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  EventIdRoute: typeof EventIdRoute
  MomentIdRoute: typeof MomentIdRoute
  MomentCreateRoute: typeof MomentCreateRoute
  VenueIdRoute: typeof VenueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moment/$id': {
      id: '/moment/$id'
      path: '/moment/$id'
      fullPath: '/moment/$id'
      preLoaderRoute: typeof MomentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moment/create': {
      id: '/moment/create'
      path: '/moment/create'
      fullPath: '/moment/create'
      preLoaderRoute: typeof MomentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/profile': {
      id: '/partner/profile'
      path: '/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/request': {
      id: '/partner/request'
      path: '/request'
      fullPath: '/partner/request'
      preLoaderRoute: typeof PartnerRequestRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/venue/$id': {
      id: '/venue/$id'
      path: '/venue/$id'
      fullPath: '/venue/$id'
      preLoaderRoute: typeof VenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venues/add': {
      id: '/admin/venues/add'
      path: '/venues/add'
      fullPath: '/admin/venues/add'
      preLoaderRoute: typeof AdminVenuesAddRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVenuesAddRoute: typeof AdminVenuesAddRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPartnersRoute: AdminPartnersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVenuesAddRoute: AdminVenuesAddRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartnerRouteChildren {
  PartnerProfileRoute: typeof PartnerProfileRoute
  PartnerRequestRoute: typeof PartnerRequestRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerProfileRoute: PartnerProfileRoute,
  PartnerRequestRoute: PartnerRequestRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  HomeRoute: HomeRoute,
  MomentsRoute: MomentsRoute,
  PartnerRoute: PartnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  EventIdRoute: EventIdRoute,
  MomentIdRoute: MomentIdRoute,
  MomentCreateRoute: MomentCreateRoute,
  VenueIdRoute: VenueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
